[package]
name = "colbert2677/lootplan"
description = "Old and modified version of dogwarrior24's LootPlan module uploaded to Wally. The package at this scope is no longer maintained."
version = "1.0.0"
license = "MIT"
authors = ["dogwarrior24", "colbert2677"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]
