[package]
name = "colbert2677/replicationutils"
description = "Old and modified version of tyridge77's ReplicationUtils module uploaded to Wally. The package at this scope is no longer maintained."
version = "2.0.0"
license = "MIT"
authors = ["tyridge77", "colbert2677"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]
Promise = "evaera/promise@4.0.0"
