[package]
name = "colbert2677/lootplan"
description = "Lightweight library for random loot generation."
version = "0.1.0"
license = "MIT"
authors = ["colbert2677"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
