[package]
name = "colbert2677/symbol"
description = "Unique object."
version = "1.0.0"
license = "MIT"
authors = ["colbert2677"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
